# Generated by Django 4.0.4 on 2023-01-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('-created_at',)},
        ),
    ]
