# Generated by Django 4.0.4 on 2023-01-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',)},
        ),
    ]
