# Generated by Django 4.0.4 on 2023-01-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_created_customer_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_card',
        ),
    ]
