# Generated by Django 4.0.4 on 2023-01-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stock_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expiryalert',
            options={'ordering': ('-expiry_alert',)},
        ),
    ]
