# Generated by Django 4.0.4 on 2023-01-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_expiryalert_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclass',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
