# Generated by Django 4.1 on 2022-11-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_alter_stock_maximum_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="item_class",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="status",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
