# Generated by Django 4.0.4 on 2022-11-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stock_item_class_alter_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='expiry_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
