# Generated by Django 4.0.4 on 2023-02-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_itemclass_name_alter_stock_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expiryalert',
            options={'ordering': ('-updated_at', 'created_at')},
        ),
        migrations.AlterField(
            model_name='stock',
            name='maximum_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reorder_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
