# Generated by Django 4.0.4 on 2022-11-07 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stock_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_class',
            field=models.ForeignKey(blank=True, default=None, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.drugclass'),
        ),
    ]
