# Generated by Django 4.0.4 on 2022-11-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stock_item_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_class',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
