# Generated by Django 4.0.4 on 2023-02-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_stock_maximum_quantity_alter_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True),
        ),
    ]
