# Generated by Django 4.0.4 on 2023-02-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_stock_cost_price_alter_stock_maximum_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
