# Generated by Django 4.0.4 on 2023-02-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
