# Generated by Django 4.0.4 on 2022-11-07 15:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0006_stock_expiry_date'),
        ('sales', '0002_rename_sales_sale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='Sales',
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ('-created_at',)},
        ),
    ]
