# Generated by Django 4.0.4 on 2022-11-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stock_expiry_date'),
        ('sales', '0003_rename_sale_sales_alter_sales_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='item_name',
        ),
        migrations.AddField(
            model_name='sales',
            name='item_name',
            field=models.ManyToManyField(to='stocks.stock'),
        ),
    ]
