# Generated by Django 4.0.4 on 2022-11-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stock_expiry_date'),
        ('sales', '0004_remove_sales_item_name_sales_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='item_name',
        ),
        migrations.AddField(
            model_name='sales',
            name='item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Sold_Item', to='stocks.stock'),
        ),
    ]
